services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    env_file:
      - ../envs/${STACKS_ENVIRONMENT}.env
    tty: true
    stdin_open: true
    volumes:
      - ${STACKS_HOME}/openldap/ldap:/data/var/lib/ldap
      - ${STACKS_HOME}/openldap/slapd.d:/etc/ldap/slapd.d
      - ${STACKS_HOME}/openldap/certs:/container/service/slapd/assets/certs
    ports:
      - 389:389
      - 636:636
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    env_file:
      - ../envs/${STACKS_ENVIRONMENT}.env
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - 8085:80
    depends_on:
      - openldap