services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${STACKS_HOME}/nginxproxymanager/data:/data
      - ${STACKS_HOME}/nginxproxymanager/letsencrypt:/etc/letsencrypt
    extends:
      file: ../../commons/compose.yml
      service: base