services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    env_file:
      - ../envs/${STACKS_ENVIRONMENT}.env
    environment:
      - NEXTCLOUD_DATADIR=${STACKS_HOME}/nextcloud/data

volumes:
  nextcloud:
    name: nextcloud_aio_mastercontainer