services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - ${STACKS_HOME}/nodered/data:/data
    restart: unless-stopped
    extends:
      file: ../../commons/compose.yml
      service: base