services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - "${STACKS_HOME}/nodered/data:/data"
    depends_on:
      - homeassistant
      - mosquitto

    restart: unless-stopped
    env_file:
      - .env