services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - ${STACKS_HOME}/homebridge:/homebridge
      - /run/dbus:/run/dbus:ro
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: 1
    extends:
      file: ../../commons/compose.yml
      service: base