services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./conf:/conf:ro
    command: ./conf/mediamtx.yml