services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${STACKS_HOME}/mosquitto/config:/mosquitto/config
      - ${STACKS_HOME}/mosquitto/data:/mosquitto/data
      - ${STACKS_HOME}/mosquitto/log:/mosquitto/log
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    extends:
      file: ../../commons/compose.yml
      service: base
    user: ${PUID:-1000}:${PGID:-1000}