services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "/mnt/stuff/mosquitto/config:/mosquitto/config"
      - "/mnt/stuff/mosquitto/data:/mosquitto/data"
      - "/mnt/stuff/mosquitto/log:/mosquitto/log"
    env_file:
      - .env
    environment:
      - TZ={TZ:-Europe/Amsterdam}
    user: "${PUID:-1000}:${PGID:-1000}"