services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    network_mode: host
    restart: always
    volumes:
      - ${STACKS_MEDIAMTX_CONFIG:-./config/mediamtx.yml}:/mediamtx.yml
    extends:
      file: ../../commons/compose.yml
      service: base
